// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/integration/lote_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_app/features/lotes/data/services/lotes_service.dart'
    as _i2;
import 'package:mobile_app/features/lotes/domain/models/lote.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LotesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLotesService extends _i1.Mock implements _i2.LotesService {
  MockLotesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createLote(_i4.Lote? lote) =>
      (super.noSuchMethod(
            Invocation.method(#createLote, [lote]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Lote>> getLotesByPredio({
    required String? predioId,
    required String? productorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLotesByPredio, [], {
              #predioId: predioId,
              #productorId: productorId,
            }),
            returnValue: _i3.Future<List<_i4.Lote>>.value(<_i4.Lote>[]),
          )
          as _i3.Future<List<_i4.Lote>>);

  @override
  _i3.Future<_i4.Lote?> getLoteById(String? loteId) =>
      (super.noSuchMethod(
            Invocation.method(#getLoteById, [loteId]),
            returnValue: _i3.Future<_i4.Lote?>.value(),
          )
          as _i3.Future<_i4.Lote?>);

  @override
  _i3.Future<void> updateLote(_i4.Lote? lote) =>
      (super.noSuchMethod(
            Invocation.method(#updateLote, [lote]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateEstadoLote({
    required String? loteId,
    required String? estadoLote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEstadoLote, [], {
              #loteId: loteId,
              #estadoLote: estadoLote,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
