// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/unit/services/informes_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile_app/features/informes/data/services/informes_service.dart'
    as _i2;
import 'package:mobile_app/features/informes/domain/models/checklist_item.dart'
    as _i4;
import 'package:mobile_app/features/informes/domain/models/checklist_respuesta.dart'
    as _i8;
import 'package:mobile_app/features/informes/domain/models/informe_sanitario.dart'
    as _i5;
import 'package:mobile_app/features/informes/domain/models/registro_especie.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InformesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInformesService extends _i1.Mock implements _i2.InformesService {
  MockInformesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ChecklistItem>> getChecklistCatalogo() =>
      (super.noSuchMethod(
            Invocation.method(#getChecklistCatalogo, []),
            returnValue: _i3.Future<List<_i4.ChecklistItem>>.value(
              <_i4.ChecklistItem>[],
            ),
          )
          as _i3.Future<List<_i4.ChecklistItem>>);

  @override
  _i3.Future<String> createInforme(_i5.InformeFitosanitario? informe) =>
      (super.noSuchMethod(
            Invocation.method(#createInforme, [informe]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createInforme, [informe]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i5.InformeFitosanitario>> getInformesByLote(
    String? loteId,
    String? productorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInformesByLote, [loteId, productorId]),
            returnValue: _i3.Future<List<_i5.InformeFitosanitario>>.value(
              <_i5.InformeFitosanitario>[],
            ),
          )
          as _i3.Future<List<_i5.InformeFitosanitario>>);

  @override
  _i3.Future<_i5.InformeFitosanitario?> getInformeById(String? informeId) =>
      (super.noSuchMethod(
            Invocation.method(#getInformeById, [informeId]),
            returnValue: _i3.Future<_i5.InformeFitosanitario?>.value(),
          )
          as _i3.Future<_i5.InformeFitosanitario?>);

  @override
  _i3.Future<bool> existeInformeParaPeriodo({
    required String? loteId,
    required String? periodoReportado,
    required int? anioReporte,
    required String? productorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#existeInformeParaPeriodo, [], {
              #loteId: loteId,
              #periodoReportado: periodoReportado,
              #anioReporte: anioReporte,
              #productorId: productorId,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateEstadoInforme({
    required String? informeId,
    required _i5.EstadoInforme? estadoInforme,
    DateTime? fechaEmision,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEstadoInforme, [], {
              #informeId: informeId,
              #estadoInforme: estadoInforme,
              #fechaEmision: fechaEmision,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveRegistroEspecie({
    required String? informeId,
    required _i7.RegistroEspecie? registro,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveRegistroEspecie, [], {
              #informeId: informeId,
              #registro: registro,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.RegistroEspecie>> getRegistrosEspecie(
    String? informeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRegistrosEspecie, [informeId]),
            returnValue: _i3.Future<List<_i7.RegistroEspecie>>.value(
              <_i7.RegistroEspecie>[],
            ),
          )
          as _i3.Future<List<_i7.RegistroEspecie>>);

  @override
  _i3.Future<void> deleteRegistroEspecie({
    required String? informeId,
    required String? registroId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRegistroEspecie, [], {
              #informeId: informeId,
              #registroId: registroId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveChecklistRespuestas({
    required String? informeId,
    required List<_i8.ChecklistRespuesta>? respuestas,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveChecklistRespuestas, [], {
              #informeId: informeId,
              #respuestas: respuestas,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.ChecklistRespuesta>> getChecklistRespuestas(
    String? informeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChecklistRespuestas, [informeId]),
            returnValue: _i3.Future<List<_i8.ChecklistRespuesta>>.value(
              <_i8.ChecklistRespuesta>[],
            ),
          )
          as _i3.Future<List<_i8.ChecklistRespuesta>>);
}
