// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2stdZRW-JenZm2BRT-Xa6FesTaBmtOKg',
    appId: '1:402460744062:web:5578118338758d9dd9bb2f',
    messagingSenderId: '402460744062',
    projectId: 'agrotrack-a435e',
    authDomain: 'agrotrack-a435e.firebaseapp.com',
    storageBucket: 'agrotrack-a435e.firebasestorage.app',
    measurementId: 'G-D37DHC6GDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-O2aeK3X_vwo0GfRK_1Sx-OUuTrGZGio',
    appId: '1:402460744062:android:1722c4fd2216413cd9bb2f',
    messagingSenderId: '402460744062',
    projectId: 'agrotrack-a435e',
    storageBucket: 'agrotrack-a435e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjkN13sSNlTANhtRItbKrjxYDypPNJVU',
    appId: '1:402460744062:ios:fd421162a75ede39d9bb2f',
    messagingSenderId: '402460744062',
    projectId: 'agrotrack-a435e',
    storageBucket: 'agrotrack-a435e.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjkN13sSNlTANhtRItbKrjxYDypPNJVU',
    appId: '1:402460744062:ios:fd421162a75ede39d9bb2f',
    messagingSenderId: '402460744062',
    projectId: 'agrotrack-a435e',
    storageBucket: 'agrotrack-a435e.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2stdZRW-JenZm2BRT-Xa6FesTaBmtOKg',
    appId: '1:402460744062:web:b4898bcc8bbae6e8d9bb2f',
    messagingSenderId: '402460744062',
    projectId: 'agrotrack-a435e',
    authDomain: 'agrotrack-a435e.firebaseapp.com',
    storageBucket: 'agrotrack-a435e.firebasestorage.app',
    measurementId: 'G-0F5GM5TW8N',
  );
}
